###
GET http://localhost:8080/jakarta-ee-project/rest/books/

###
GET http://localhost:8080/jakarta-ee-project/rest/books/1

###
POST http://localhost:8080/jakarta-ee-project/rest/books/
Content-Type: application/json

{
    "nome":"Teste"
}


###
PUT http://localhost:8080/jakarta-ee-project/rest/books/1
Content-Type: application/json

{
    "nome":"Teste 2"
}


### ORDER ###

###
GET http://localhost:8080/jakarta-ee-project/rest/order/


###
POST http://localhost:8080/jakarta-ee-project/rest/order/
Content-Type: application/json

{
    "book":{
        "id": 1
    }
}


###
POST http://localhost:8080/jakarta-ee-project/rest/order/send-to-payment/1602

